import { AppDefinition, RecordDefinition } from "@/types/schema";

export function createSeedApp(): AppDefinition {
  return {
    id: "app_gowthamtest",
    name: "Gowtham Test",
    linkName: "gowthamtest",
    description: "Enterprise sample workspace demonstrating Forms, Lookups, Subforms, Reports, and Workflow Calculations.",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    settings: {
      theme: "light",
      accentColor: "#2563eb",
    },
    forms: [
      {
        id: "form_city",
        name: "City",
        linkName: "city",
        description: "Master list of cities and regions",
        columns: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        fields: [
          {
            id: "field_city_name",
            label: "City Name",
            linkName: "city_name",
            type: "text",
            required: true,
            placeholder: "e.g. Bengaluru",
          },
          {
            id: "field_city_state",
            label: "State",
            linkName: "state",
            type: "text",
            required: true,
            placeholder: "e.g. Karnataka",
          },
          {
            id: "field_city_country",
            label: "Country",
            linkName: "country",
            type: "text",
            defaultValue: "India",
          },
        ],
      },
      {
        id: "form_customer",
        name: "Customer",
        linkName: "customer",
        description: "Customer accounts and contact details",
        columns: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        fields: [
          {
            id: "field_cust_id",
            label: "Customer Code",
            linkName: "customer_code",
            type: "autonumber",
            autonumber: {
              prefix: "CUS-",
              startNumber: 1,
              digits: 5,
            },
          },
          {
            id: "field_cust_name",
            label: "Customer Name",
            linkName: "customer_name",
            type: "text",
            required: true,
            placeholder: "e.g. Gowtham Raj",
          },
          {
            id: "field_cust_email",
            label: "Email",
            linkName: "email",
            type: "email",
            required: true,
            placeholder: "gowtham@example.com",
          },
          {
            id: "field_cust_phone",
            label: "Phone",
            linkName: "phone",
            type: "phone",
            placeholder: "+91 98765 43210",
          },
          {
            id: "field_cust_city",
            label: "City",
            linkName: "city",
            type: "lookup",
            lookup: {
              targetFormId: "form_city",
              displayFieldId: "field_city_name",
              valueFieldId: "id",
              relationshipType: "lookup",
            },
          },
          {
            id: "field_cust_salary",
            label: "Annual Budget",
            linkName: "budget",
            type: "currency",
            currencySymbol: "₹",
            decimalPlaces: 2,
            defaultValue: 500000,
          },
          {
            id: "field_cust_discount",
            label: "Discount %",
            linkName: "discount",
            type: "percentage",
            decimalPlaces: 1,
            defaultValue: 10,
          },
          {
            id: "field_cust_status",
            label: "Status",
            linkName: "status",
            type: "dropdown",
            options: ["Active", "Lead", "Inactive"],
            defaultValue: "Active",
          },
          {
            id: "field_cust_active",
            label: "Active Client",
            linkName: "active",
            type: "checkbox",
            defaultValue: true,
          },
        ],
      },
      {
        id: "form_product",
        name: "Product",
        linkName: "product",
        description: "Inventory products and catalog",
        columns: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        fields: [
          {
            id: "field_prod_sku",
            label: "Product SKU",
            linkName: "sku",
            type: "autonumber",
            autonumber: {
              prefix: "PRD-",
              startNumber: 101,
              digits: 4,
            },
          },
          {
            id: "field_prod_name",
            label: "Product Name",
            linkName: "product_name",
            type: "text",
            required: true,
            placeholder: "e.g. Cloud Enterprise Suite",
          },
          {
            id: "field_prod_category",
            label: "Category",
            linkName: "category",
            type: "dropdown",
            options: ["Software", "Hardware", "Consulting", "Services"],
            defaultValue: "Software",
          },
          {
            id: "field_prod_price",
            label: "Unit Price",
            linkName: "price",
            type: "currency",
            currencySymbol: "₹",
            decimalPlaces: 2,
            required: true,
            defaultValue: 15000,
          },
          {
            id: "field_prod_stock",
            label: "Stock Quantity",
            linkName: "stock",
            type: "number",
            defaultValue: 50,
          },
        ],
      },
      {
        id: "form_invoice",
        name: "Invoice",
        linkName: "invoice",
        description: "Invoices with line items subform and lookup calculations",
        columns: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        fields: [
          {
            id: "field_inv_number",
            label: "Invoice Number",
            linkName: "invoice_number",
            type: "autonumber",
            autonumber: {
              prefix: "INV-2026-",
              startNumber: 1,
              digits: 4,
            },
          },
          {
            id: "field_inv_customer",
            label: "Customer",
            linkName: "customer",
            type: "lookup",
            required: true,
            lookup: {
              targetFormId: "form_customer",
              displayFieldId: "field_cust_name",
              valueFieldId: "id",
              relationshipType: "lookup",
            },
          },
          {
            id: "field_inv_date",
            label: "Invoice Date",
            linkName: "invoice_date",
            type: "date",
            defaultValue: "2026-09-19",
          },
          {
            id: "field_inv_items",
            label: "Invoice Items",
            linkName: "items",
            type: "subform",
            subform: {
              sourceType: "inline",
              columns: [
                {
                  id: "col_item_product",
                  label: "Product",
                  linkName: "product",
                  type: "lookup",
                  required: true,
                  lookup: {
                    targetFormId: "form_product",
                    displayFieldId: "field_prod_name",
                    valueFieldId: "id",
                    relationshipType: "lookup",
                  },
                },
                {
                  id: "col_item_quantity",
                  label: "Quantity",
                  linkName: "quantity",
                  type: "number",
                  required: true,
                  defaultValue: 1,
                },
                {
                  id: "col_item_rate",
                  label: "Rate",
                  linkName: "rate",
                  type: "currency",
                  currencySymbol: "₹",
                  required: true,
                  defaultValue: 100,
                },
                {
                  id: "col_item_amount",
                  label: "Amount",
                  linkName: "amount",
                  type: "currency",
                  currencySymbol: "₹",
                  defaultValue: 100,
                },
              ],
            },
          },
          {
            id: "field_inv_subtotal",
            label: "Subtotal",
            linkName: "subtotal",
            type: "currency",
            currencySymbol: "₹",
            readonly: true,
            defaultValue: 0,
          },
          {
            id: "field_inv_tax",
            label: "Tax Rate %",
            linkName: "tax_rate",
            type: "percentage",
            defaultValue: 18,
          },
          {
            id: "field_inv_total",
            label: "Grand Total",
            linkName: "total_amount",
            type: "currency",
            currencySymbol: "₹",
            readonly: true,
            defaultValue: 0,
          },
        ],
      },
      {
        id: "form_purchase",
        name: "Purchase Entry",
        linkName: "purchase",
        description: "Inward purchases received from suppliers and vendors (Stock Inflow)",
        columns: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        fields: [
          {
            id: "field_pur_id",
            label: "Purchase Ref #",
            linkName: "purchase_no",
            type: "autonumber",
            autonumber: {
              prefix: "PUR-2026-",
              startNumber: 101,
              digits: 4,
            },
          },
          {
            id: "field_pur_product",
            label: "Purchased Product",
            linkName: "product",
            type: "lookup",
            required: true,
            lookup: {
              targetFormId: "form_product",
              displayFieldId: "field_prod_name",
              valueFieldId: "id",
              relationshipType: "lookup",
            },
          },
          {
            id: "field_pur_qty",
            label: "Quantity Purchased",
            linkName: "quantity",
            type: "number",
            required: true,
            defaultValue: 10,
          },
          {
            id: "field_pur_unit_price",
            label: "Unit Cost",
            linkName: "unit_price",
            type: "currency",
            currencySymbol: "₹",
            decimalPlaces: 2,
            required: true,
            defaultValue: 1500,
          },
          {
            id: "field_pur_total_cost",
            label: "Total Inward Cost",
            linkName: "total_cost",
            type: "currency",
            currencySymbol: "₹",
            decimalPlaces: 2,
            readonly: true,
            defaultValue: 15000,
          },
          {
            id: "field_pur_supplier",
            label: "Supplier / Vendor",
            linkName: "supplier",
            type: "text",
            required: true,
            defaultValue: "National Components Ltd",
          },
          {
            id: "field_pur_date",
            label: "Purchase Date",
            linkName: "purchase_date",
            type: "date",
            defaultValue: "2026-09-18",
          },
          {
            id: "field_pur_notes",
            label: "Invoice Notes",
            linkName: "notes",
            type: "textarea",
          },
        ],
      },
      {
        id: "form_usage",
        name: "Material Usage",
        linkName: "usage",
        description: "Outward material consumption tracking by department (Stock Outflow)",
        columns: 2,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        fields: [
          {
            id: "field_use_id",
            label: "Usage Voucher #",
            linkName: "voucher_no",
            type: "autonumber",
            autonumber: {
              prefix: "USE-2026-",
              startNumber: 201,
              digits: 4,
            },
          },
          {
            id: "field_use_product",
            label: "Used Product",
            linkName: "product",
            type: "lookup",
            required: true,
            lookup: {
              targetFormId: "form_product",
              displayFieldId: "field_prod_name",
              valueFieldId: "id",
              relationshipType: "lookup",
            },
          },
          {
            id: "field_use_qty",
            label: "Quantity Used",
            linkName: "quantity_used",
            type: "number",
            required: true,
            defaultValue: 5,
          },
          {
            id: "field_use_department",
            label: "Department",
            linkName: "department",
            type: "dropdown",
            options: ["Production", "R&D Lab", "Maintenance", "Sales Demo"],
            defaultValue: "Production",
          },
          {
            id: "field_use_date",
            label: "Usage Date",
            linkName: "usage_date",
            type: "date",
            defaultValue: "2026-09-19",
          },
          {
            id: "field_use_reason",
            label: "Work Order / Purpose",
            linkName: "work_order",
            type: "text",
            defaultValue: "Batch Production Order #B402",
          },
          {
            id: "field_use_notes",
            label: "Remarks / Observations",
            linkName: "notes",
            type: "textarea",
          },
        ],
      },
    ],
    reports: [
      {
        id: "rep_customer",
        name: "Customer Report",
        linkName: "customer_report",
        sourceFormId: "form_customer",
        pageSize: 10,
        quickFilterFieldIds: ["field_cust_status", "field_cust_city"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        columns: [
          { fieldId: "field_cust_id", label: "Customer Code", visible: true, order: 0 },
          { fieldId: "field_cust_name", label: "Customer Name", visible: true, order: 1 },
          { fieldId: "field_cust_email", label: "Email", visible: true, order: 2 },
          { fieldId: "field_cust_phone", label: "Phone", visible: true, order: 3 },
          { fieldId: "field_cust_city", label: "City", visible: true, order: 4 },
          { fieldId: "field_cust_salary", label: "Budget", visible: true, order: 5 },
          { fieldId: "field_cust_status", label: "Status", visible: true, order: 6 },
        ],
      },
      {
        id: "rep_city",
        name: "City Report",
        linkName: "city_report",
        sourceFormId: "form_city",
        pageSize: 10,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        columns: [
          { fieldId: "field_city_name", label: "City Name", visible: true, order: 0 },
          { fieldId: "field_city_state", label: "State", visible: true, order: 1 },
          { fieldId: "field_city_country", label: "Country", visible: true, order: 2 },
        ],
      },
      {
        id: "rep_product",
        name: "Product Report",
        linkName: "product_report",
        sourceFormId: "form_product",
        pageSize: 10,
        quickFilterFieldIds: ["field_prod_category"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        columns: [
          { fieldId: "field_prod_sku", label: "SKU", visible: true, order: 0 },
          { fieldId: "field_prod_name", label: "Product Name", visible: true, order: 1 },
          { fieldId: "field_prod_category", label: "Category", visible: true, order: 2 },
          { fieldId: "field_prod_price", label: "Price", visible: true, order: 3 },
          { fieldId: "field_prod_stock", label: "Stock", visible: true, order: 4 },
        ],
      },
      {
        id: "rep_invoice",
        name: "Invoice Report",
        linkName: "invoice_report",
        sourceFormId: "form_invoice",
        pageSize: 10,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        columns: [
          { fieldId: "field_inv_number", label: "Invoice #", visible: true, order: 0 },
          { fieldId: "field_inv_customer", label: "Customer", visible: true, order: 1 },
          { fieldId: "field_inv_date", label: "Date", visible: true, order: 2 },
          { fieldId: "field_inv_total", label: "Grand Total", visible: true, order: 3 },
        ],
      },
      {
        id: "rep_purchase",
        name: "Purchase Entries Report",
        linkName: "purchase_report",
        sourceFormId: "form_purchase",
        pageSize: 10,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        columns: [
          { fieldId: "field_pur_id", label: "Ref #", visible: true, order: 0 },
          { fieldId: "field_pur_product", label: "Product", visible: true, order: 1 },
          { fieldId: "field_pur_qty", label: "Quantity", visible: true, order: 2 },
          { fieldId: "field_pur_unit_price", label: "Unit Cost", visible: true, order: 3 },
          { fieldId: "field_pur_total_cost", label: "Total Cost", visible: true, order: 4 },
          { fieldId: "field_pur_supplier", label: "Supplier", visible: true, order: 5 },
          { fieldId: "field_pur_date", label: "Date", visible: true, order: 6 },
        ],
      },
      {
        id: "rep_usage",
        name: "Material Usage Report",
        linkName: "usage_report",
        sourceFormId: "form_usage",
        pageSize: 10,
        quickFilterFieldIds: ["field_use_department"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        columns: [
          { fieldId: "field_use_id", label: "Voucher #", visible: true, order: 0 },
          { fieldId: "field_use_product", label: "Product", visible: true, order: 1 },
          { fieldId: "field_use_qty", label: "Quantity Used", visible: true, order: 2 },
          { fieldId: "field_use_department", label: "Department", visible: true, order: 3 },
          { fieldId: "field_use_date", label: "Date", visible: true, order: 4 },
          { fieldId: "field_use_reason", label: "Work Order", visible: true, order: 5 },
        ],
      },
      {
        id: "rep_reconciliation",
        name: "Stock & Usage Reconciliation",
        linkName: "stock_reconciliation",
        sourceFormId: "form_product",
        reportType: "reconciliation",
        reconciliationConfig: {
          primaryFormId: "form_product",
          inflowFormId: "form_purchase",
          inflowMatchFieldId: "field_pur_product",
          inflowQtyFieldId: "field_pur_qty",
          outflowFormId: "form_usage",
          outflowMatchFieldId: "field_use_product",
          outflowQtyFieldId: "field_use_qty",
        },
        quickFilterFieldIds: ["field_prod_category"],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        columns: [],
      },
    ],
    pages: [
      {
        id: "page_dashboard",
        name: "Dashboard",
        linkName: "dashboard",
        description: "Executive application overview and real-time business intelligence",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        components: [
          {
            id: "comp_hero",
            type: "heading",
            props: {
              title: "Executive Business Dashboard",
              subtitle: "Live runtime analytics powered by your low-code application builder schema.",
            },
          },
          {
            id: "comp_stats",
            type: "stat_card",
            props: {
              stats: [
                {
                  label: "Active Customers",
                  value: "{{customer.count}}",
                  change: "+12.5%",
                },
                {
                  label: "Products in Catalog",
                  value: "{{product.count}}",
                  change: "+5.0%",
                },
                {
                  label: "Total Purchases",
                  value: "{{purchase.count}}",
                  change: "+14.2%",
                },
                {
                  label: "Total Usage Entries",
                  value: "{{usage.count}}",
                  change: "+22.1%",
                },
              ],
            },
          },
          {
            id: "comp_chart_invoices",
            type: "chart",
            props: {
              title: "Revenue Distribution by Customer",
              chartType: "donut",
              formId: "form_invoice",
              groupByFieldId: "field_inv_customer",
              metric: "sum",
              measureFieldId: "field_inv_total",
            },
          },
          {
            id: "comp_chart_products",
            type: "chart",
            props: {
              title: "Inventory Stock Level by Product",
              chartType: "bar",
              formId: "form_product",
              groupByFieldId: "field_prod_name",
              metric: "sum",
              measureFieldId: "field_prod_stock",
            },
          },
          {
            id: "comp_recent_invoices",
            type: "report_embed",
            props: {
              reportId: "rep_invoice",
            },
          },
        ],
      },
    ],
    workflows: [
      {
        id: "wf_invoice_empty_customer",
        name: "Validate Customer on Submit with Popup Alert",
        description: "Blocks submission and triggers popup alert if Customer is blank",
        formId: "form_invoice",
        active: true,
        mode: "code",
        trigger: {
          type: "onSubmit",
        },
        codeScript: `// On Submit Validation: Block and show popup if customer is empty
if (!customer || customer == "") {
  showPopup("Invoice Submission Blocked: Please choose a Customer for this invoice before submitting.");
  blockSubmit();
}`,
        actions: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "wf_discount_check",
        name: "High Customer Discount Approval Notice",
        description: "Alerts when customer discount exceeds 30%",
        formId: "form_customer",
        active: true,
        mode: "code",
        trigger: {
          type: "onUserInput",
          fieldId: "field_cust_discount",
        },
        codeScript: `// Manager Discount Authorization Warning
if (discount > 30) {
  showPopup("Special Authorization: Customer discount above 30% requires branch manager approval.");
}`,
        actions: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "wf_invoice_item_calc",
        name: "Calculate Subform Item Amount",
        description: "Computes Amount = Quantity * Rate automatically",
        formId: "form_invoice",
        active: true,
        mode: "code",
        trigger: {
          type: "onUserInput",
          fieldId: "col_item_quantity",
        },
        codeScript: `// Real-time Line Item Amount Calculation
amount = quantity * rate;`,
        actions: [
          {
            id: "act_calc_amount",
            type: "calculateValue",
            targetFieldId: "col_item_amount",
            expression: "quantity * rate",
          },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "wf_pur_calc_total",
        name: "Auto-Calculate Purchase Total Cost (No Code)",
        description: "100% No-Code Calculation: Total Cost = Quantity * Unit Cost",
        formId: "form_purchase",
        active: true,
        mode: "visual",
        trigger: {
          type: "onUserInput",
          fieldId: "field_pur_qty",
        },
        actions: [
          {
            id: "act_pur_calc",
            type: "calculateValue",
            targetFieldId: "field_pur_total_cost",
            visualCalculation: {
              operand1FieldId: "field_pur_qty",
              operation: "*",
              operand2Type: "field",
              operand2FieldId: "field_pur_unit_price",
            },
          },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "wf_pur_calc_from_price",
        name: "Auto-Calculate Purchase Total from Unit Price (No Code)",
        description: "100% No-Code Calculation when Unit Cost changes",
        formId: "form_purchase",
        active: true,
        mode: "visual",
        trigger: {
          type: "onUserInput",
          fieldId: "field_pur_unit_price",
        },
        actions: [
          {
            id: "act_pur_calc_price",
            type: "calculateValue",
            targetFieldId: "field_pur_total_cost",
            visualCalculation: {
              operand1FieldId: "field_pur_qty",
              operation: "*",
              operand2Type: "field",
              operand2FieldId: "field_pur_unit_price",
            },
          },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "wf_pur_block_zero_qty",
        name: "Block Zero Purchase Quantity (No Code)",
        description: "100% No-Code Validation: Blocks submit if Quantity < 1",
        formId: "form_purchase",
        active: true,
        mode: "visual",
        trigger: {
          type: "onSubmit",
        },
        actions: [
          {
            id: "act_pur_validate",
            type: "showPopup",
            message: "Validation Error: Purchase Quantity must be at least 1 unit to submit entry.",
            popupType: "error",
            blockSubmitOnPopup: true,
            visualConditions: [
              {
                id: "cond_pur_qty_min",
                fieldId: "field_pur_qty",
                operator: "less_than",
                compareType: "literal",
                value: 1,
              },
            ],
          },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: "wf_use_block_zero_qty",
        name: "Block Zero Material Usage Quantity (No Code)",
        description: "100% No-Code Validation: Blocks submit if Quantity Used < 1",
        formId: "form_usage",
        active: true,
        mode: "visual",
        trigger: {
          type: "onSubmit",
        },
        actions: [
          {
            id: "act_use_validate",
            type: "showPopup",
            message: "Validation Error: Material Usage Quantity must be at least 1 unit.",
            popupType: "error",
            blockSubmitOnPopup: true,
            visualConditions: [
              {
                id: "cond_use_qty_min",
                fieldId: "field_use_qty",
                operator: "less_than",
                compareType: "literal",
                value: 1,
              },
            ],
          },
        ],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    relationships: [
      {
        id: "rel_cust_city",
        sourceFormId: "form_customer",
        sourceFieldId: "field_cust_city",
        targetFormId: "form_city",
        targetFieldId: "field_city_name",
        type: "lookup",
      },
      {
        id: "rel_inv_cust",
        sourceFormId: "form_invoice",
        sourceFieldId: "field_inv_customer",
        targetFormId: "form_customer",
        targetFieldId: "field_cust_name",
        type: "lookup",
      },
      {
        id: "rel_inv_subform",
        sourceFormId: "form_invoice",
        sourceFieldId: "field_inv_items",
        targetFormId: "form_product",
        targetFieldId: "field_prod_name",
        type: "subform",
      },
      {
        id: "rel_pur_prod",
        sourceFormId: "form_purchase",
        sourceFieldId: "field_pur_product",
        targetFormId: "form_product",
        targetFieldId: "field_prod_name",
        type: "lookup",
      },
      {
        id: "rel_use_prod",
        sourceFormId: "form_usage",
        sourceFieldId: "field_use_product",
        targetFormId: "form_product",
        targetFieldId: "field_prod_name",
        type: "lookup",
      },
    ],
  };
}

export function createSeedRecords(appId: string): Record<string, RecordDefinition[]> {
  const now = new Date().toISOString();

  const cities: RecordDefinition[] = [
    {
      id: "rec_city_1",
      appId,
      formId: "form_city",
      createdAt: now,
      updatedAt: now,
      data: {
        field_city_name: "Bengaluru",
        field_city_state: "Karnataka",
        field_city_country: "India",
      },
    },
    {
      id: "rec_city_2",
      appId,
      formId: "form_city",
      createdAt: now,
      updatedAt: now,
      data: {
        field_city_name: "Chennai",
        field_city_state: "Tamil Nadu",
        field_city_country: "India",
      },
    },
    {
      id: "rec_city_3",
      appId,
      formId: "form_city",
      createdAt: now,
      updatedAt: now,
      data: {
        field_city_name: "Hyderabad",
        field_city_state: "Telangana",
        field_city_country: "India",
      },
    },
    {
      id: "rec_city_4",
      appId,
      formId: "form_city",
      createdAt: now,
      updatedAt: now,
      data: {
        field_city_name: "Mumbai",
        field_city_state: "Maharashtra",
        field_city_country: "India",
      },
    },
  ];

  const customers: RecordDefinition[] = [
    {
      id: "rec_cust_1",
      appId,
      formId: "form_customer",
      createdAt: now,
      updatedAt: now,
      data: {
        field_cust_id: "CUS-00001",
        field_cust_name: "Gowtham Raj",
        field_cust_email: "gowtham@example.com",
        field_cust_phone: "+91 9876543210",
        field_cust_city: "rec_city_1", // References Bengaluru
        field_cust_salary: 850000,
        field_cust_discount: 15,
        field_cust_status: "Active",
        field_cust_active: true,
      },
    },
    {
      id: "rec_cust_2",
      appId,
      formId: "form_customer",
      createdAt: now,
      updatedAt: now,
      data: {
        field_cust_id: "CUS-00002",
        field_cust_name: "Kumar Sundaram",
        field_cust_email: "kumar@example.com",
        field_cust_phone: "+91 9841234567",
        field_cust_city: "rec_city_2", // References Chennai
        field_cust_salary: 620000,
        field_cust_discount: 10,
        field_cust_status: "Active",
        field_cust_active: true,
      },
    },
    {
      id: "rec_cust_3",
      appId,
      formId: "form_customer",
      createdAt: now,
      updatedAt: now,
      data: {
        field_cust_id: "CUS-00003",
        field_cust_name: "Arun Prakash",
        field_cust_email: "arun.p@example.com",
        field_cust_phone: "+91 9712345678",
        field_cust_city: "rec_city_3", // References Hyderabad
        field_cust_salary: 450000,
        field_cust_discount: 5,
        field_cust_status: "Lead",
        field_cust_active: true,
      },
    },
  ];

  const products: RecordDefinition[] = [
    {
      id: "rec_prod_1",
      appId,
      formId: "form_product",
      createdAt: now,
      updatedAt: now,
      data: {
        field_prod_sku: "PRD-0101",
        field_prod_name: "Enterprise Cloud ERP",
        field_prod_category: "Software",
        field_prod_price: 45000,
        field_prod_stock: 50,
      },
    },
    {
      id: "rec_prod_2",
      appId,
      formId: "form_product",
      createdAt: now,
      updatedAt: now,
      data: {
        field_prod_sku: "PRD-0102",
        field_prod_name: "Developer Pro Workstation",
        field_prod_category: "Hardware",
        field_prod_price: 95000,
        field_prod_stock: 13,
      },
    },
    {
      id: "rec_prod_3",
      appId,
      formId: "form_product",
      createdAt: now,
      updatedAt: now,
      data: {
        field_prod_sku: "PRD-0103",
        field_prod_name: "Architecture Consultation",
        field_prod_category: "Consulting",
        field_prod_price: 25000,
        field_prod_stock: 2,
      },
    },
  ];

  const invoices: RecordDefinition[] = [
    {
      id: "rec_inv_1",
      appId,
      formId: "form_invoice",
      createdAt: now,
      updatedAt: now,
      data: {
        field_inv_number: "INV-2026-0001",
        field_inv_customer: "rec_cust_1", // Gowtham Raj
        field_inv_date: "2026-09-19",
        field_inv_items: [
          {
            id: "row_1",
            col_item_product: "rec_prod_1", // Enterprise Cloud ERP
            col_item_quantity: 2,
            col_item_rate: 45000,
            col_item_amount: 90000,
          },
          {
            id: "row_2",
            col_item_product: "rec_prod_3", // Architecture Consultation
            col_item_quantity: 1,
            col_item_rate: 25000,
            col_item_amount: 25000,
          },
        ],
        field_inv_subtotal: 115000,
        field_inv_tax: 18,
        field_inv_total: 135700,
      },
    },
  ];

  // Matched Inward Purchases (Purchased stock entries)
  const purchases: RecordDefinition[] = [
    {
      id: "rec_pur_1",
      appId,
      formId: "form_purchase",
      createdAt: "2026-09-10T10:00:00.000Z",
      updatedAt: "2026-09-10T10:00:00.000Z",
      data: {
        field_pur_id: "PUR-2026-0101",
        field_pur_product: "rec_prod_1", // Enterprise Cloud ERP
        field_pur_qty: 50,
        field_pur_unit_price: 35000,
        field_pur_total_cost: 1750000,
        field_pur_supplier: "Global Cloud Distributors Ltd",
        field_pur_date: "2026-09-10",
        field_pur_notes: "Initial batch of corporate server license seats",
      },
    },
    {
      id: "rec_pur_2",
      appId,
      formId: "form_purchase",
      createdAt: "2026-09-14T11:30:00.000Z",
      updatedAt: "2026-09-14T11:30:00.000Z",
      data: {
        field_pur_id: "PUR-2026-0102",
        field_pur_product: "rec_prod_1", // Enterprise Cloud ERP
        field_pur_qty: 30,
        field_pur_unit_price: 35000,
        field_pur_total_cost: 1050000,
        field_pur_supplier: "Cloud Dynamics Asia",
        field_pur_date: "2026-09-14",
        field_pur_notes: "Expansion licenses for Q3 deployment",
      },
    },
    {
      id: "rec_pur_3",
      appId,
      formId: "form_purchase",
      createdAt: "2026-09-12T09:15:00.000Z",
      updatedAt: "2026-09-12T09:15:00.000Z",
      data: {
        field_pur_id: "PUR-2026-0103",
        field_pur_product: "rec_prod_2", // Developer Pro Workstation
        field_pur_qty: 20,
        field_pur_unit_price: 85000,
        field_pur_total_cost: 1700000,
        field_pur_supplier: "Dell Direct Enterprise",
        field_pur_date: "2026-09-12",
        field_pur_notes: "High-spec workstations with 64GB RAM",
      },
    },
    {
      id: "rec_pur_4",
      appId,
      formId: "form_purchase",
      createdAt: "2026-09-16T14:45:00.000Z",
      updatedAt: "2026-09-16T14:45:00.000Z",
      data: {
        field_pur_id: "PUR-2026-0104",
        field_pur_product: "rec_prod_2", // Developer Pro Workstation
        field_pur_qty: 15,
        field_pur_unit_price: 85000,
        field_pur_total_cost: 1275000,
        field_pur_supplier: "HP Commercial Solutions",
        field_pur_date: "2026-09-16",
        field_pur_notes: "Secondary procurement batch",
      },
    },
    {
      id: "rec_pur_5",
      appId,
      formId: "form_purchase",
      createdAt: "2026-09-11T13:00:00.000Z",
      updatedAt: "2026-09-11T13:00:00.000Z",
      data: {
        field_pur_id: "PUR-2026-0105",
        field_pur_product: "rec_prod_3", // Architecture Consultation
        field_pur_qty: 40,
        field_pur_unit_price: 20000,
        field_pur_total_cost: 800000,
        field_pur_supplier: "Zeta Consulting Guild",
        field_pur_date: "2026-09-11",
        field_pur_notes: "Specialized architect consulting hours retainer",
      },
    },
  ];

  // Matched Outward Material Usages (Consumed stock entries)
  const usages: RecordDefinition[] = [
    {
      id: "rec_use_1",
      appId,
      formId: "form_usage",
      createdAt: "2026-09-15T15:20:00.000Z",
      updatedAt: "2026-09-15T15:20:00.000Z",
      data: {
        field_use_id: "USE-2026-0201",
        field_use_product: "rec_prod_1", // Enterprise Cloud ERP
        field_use_qty: 18,
        field_use_department: "Production",
        field_use_date: "2026-09-15",
        field_use_reason: "Deployed for Client Onboarding Project Delta",
        field_use_notes: "Allocated to Production deployment team",
      },
    },
    {
      id: "rec_use_2",
      appId,
      formId: "form_usage",
      createdAt: "2026-09-18T16:00:00.000Z",
      updatedAt: "2026-09-18T16:00:00.000Z",
      data: {
        field_use_id: "USE-2026-0202",
        field_use_product: "rec_prod_1", // Enterprise Cloud ERP
        field_use_qty: 12,
        field_use_department: "R&D Lab",
        field_use_date: "2026-09-18",
        field_use_reason: "Internal Test Sandbox & Staging Environment",
        field_use_notes: "Testing new feature rollout",
      },
    },
    {
      id: "rec_use_3",
      appId,
      formId: "form_usage",
      createdAt: "2026-09-15T11:00:00.000Z",
      updatedAt: "2026-09-15T11:00:00.000Z",
      data: {
        field_use_id: "USE-2026-0203",
        field_use_product: "rec_prod_2", // Developer Pro Workstation
        field_use_qty: 10,
        field_use_department: "Production",
        field_use_date: "2026-09-15",
        field_use_reason: "New engineering team workstation dispatch",
        field_use_notes: "Assigned to backend team recruits",
      },
    },
    {
      id: "rec_use_4",
      appId,
      formId: "form_usage",
      createdAt: "2026-09-18T10:30:00.000Z",
      updatedAt: "2026-09-18T10:30:00.000Z",
      data: {
        field_use_id: "USE-2026-0204",
        field_use_product: "rec_prod_2", // Developer Pro Workstation
        field_use_qty: 12,
        field_use_department: "R&D Lab",
        field_use_date: "2026-09-18",
        field_use_reason: "High Performance AI Training Station",
        field_use_notes: "Allocated to ML engineers",
      },
    },
    {
      id: "rec_use_5",
      appId,
      formId: "form_usage",
      createdAt: "2026-09-17T17:00:00.000Z",
      updatedAt: "2026-09-17T17:00:00.000Z",
      data: {
        field_use_id: "USE-2026-0205",
        field_use_product: "rec_prod_3", // Architecture Consultation
        field_use_qty: 38,
        field_use_department: "Sales Demo",
        field_use_date: "2026-09-17",
        field_use_reason: "Enterprise Client RFP Solutioning",
        field_use_notes: "Consulting hours expended for Government RFP bid",
      },
    },
  ];

  return {
    [`${appId}_form_city`]: cities,
    [`${appId}_form_customer`]: customers,
    [`${appId}_form_product`]: products,
    [`${appId}_form_invoice`]: invoices,
    [`${appId}_form_purchase`]: purchases,
    [`${appId}_form_usage`]: usages,
  };
}
