"use client";

import React from "react";
import { FieldDefinition, WorkflowDefinition } from "@/types/schema";
import { Input, Select } from "@/components/ui/FormControls";
import { LookupField } from "./LookupField";
import { SubformField } from "./SubformField";

interface DynamicFieldProps {
  field: FieldDefinition;
  value: any;
  onChange: (value: any) => void;
  error?: string;
  isReadonly?: boolean;
  isHidden?: boolean;
  workflows?: WorkflowDefinition[];
}

export const DynamicField: React.FC<DynamicFieldProps> = ({
  field,
  value,
  onChange,
  error,
  isReadonly = false,
  isHidden = false,
  workflows = [],
}) => {
  if (isHidden || field.hidden) return null;

  const disabled = isReadonly || field.readonly;

  // 1. Lookup Field
  if (field.type === "lookup" && field.lookup) {
    return (
      <LookupField
        label={field.label}
        value={value || ""}
        onChange={onChange}
        lookupConfig={field.lookup}
        error={error}
        disabled={disabled}
        required={field.required}
      />
    );
  }

  // 2. Subform Field
  if (field.type === "subform" && field.subform) {
    return (
      <SubformField
        label={field.label}
        columns={field.subform.columns || []}
        rows={Array.isArray(value) ? value : []}
        onChange={onChange}
        workflows={workflows}
        disabled={disabled}
      />
    );
  }

  // 3. Auto Number Field (computed sequentially)
  if (field.type === "autonumber") {
    return (
      <Input
        label={field.label}
        value={value || "(Auto-generated upon save)"}
        disabled
        helperText="Sequential identifier generated by application"
      />
    );
  }

  // 4. Checkbox Field
  if (field.type === "checkbox") {
    return (
      <div className="w-full space-y-1 pt-2">
        <label className="flex items-center gap-2.5 text-slate-800 text-xs font-medium cursor-pointer">
          <input
            type="checkbox"
            disabled={disabled}
            checked={Boolean(value)}
            onChange={(e) => onChange(e.target.checked)}
            className="w-4 h-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500 cursor-pointer disabled:opacity-50"
          />
          <span>{field.label}</span>
          {field.required && <span className="text-rose-500">*</span>}
        </label>
        {field.description && <p className="text-[11px] text-slate-400 pl-6">{field.description}</p>}
        {error && <p className="text-xs text-rose-600 font-medium pl-6">{error}</p>}
      </div>
    );
  }

  // 5. Multi Line (textarea)
  if (field.type === "textarea") {
    return (
      <div className="w-full space-y-1.5">
        <label className="block text-xs font-medium text-slate-700">
          {field.label}
          {field.required && <span className="text-rose-500 ml-1">*</span>}
        </label>
        <textarea
          rows={3}
          disabled={disabled}
          value={value || ""}
          onChange={(e) => onChange(e.target.value)}
          placeholder={field.placeholder || ""}
          className={`w-full text-xs p-2.5 rounded-lg border ${
            error
              ? "border-rose-400 focus:ring-rose-300 ring-1 ring-rose-300"
              : "border-slate-300 focus:ring-blue-500"
          } focus:outline-none focus:ring-2 bg-white disabled:bg-slate-50 disabled:text-slate-500`}
        />
        {error && <p className="text-xs text-rose-600 font-medium">{error}</p>}
      </div>
    );
  }

  // 6. Dropdown
  if (field.type === "dropdown") {
    return (
      <Select
        label={field.label}
        value={value || ""}
        required={field.required}
        disabled={disabled}
        error={error}
        helperText={field.description}
        onChange={(e) => onChange(e.target.value)}
      >
        <option value="">Select {field.label}...</option>
        {(field.options || []).map((opt) => (
          <option key={opt} value={opt}>
            {opt}
          </option>
        ))}
      </Select>
    );
  }

  // 7. Radio
  if (field.type === "radio") {
    return (
      <div className="w-full space-y-2">
        <label className="block text-xs font-medium text-slate-700">
          {field.label}
          {field.required && <span className="text-rose-500 ml-1">*</span>}
        </label>
        <div className="flex items-center gap-4 flex-wrap">
          {(field.options || []).map((opt) => (
            <label key={opt} className="flex items-center gap-1.5 text-xs text-slate-700 cursor-pointer">
              <input
                type="radio"
                name={field.id}
                disabled={disabled}
                value={opt}
                checked={value === opt}
                onChange={(e) => onChange(e.target.value)}
                className="text-blue-600 focus:ring-blue-500"
              />
              <span>{opt}</span>
            </label>
          ))}
        </div>
        {error && <p className="text-xs text-rose-600 font-medium">{error}</p>}
      </div>
    );
  }

  // 8. Currency Field
  if (field.type === "currency") {
    return (
      <Input
        label={field.label}
        type="number"
        step="any"
        required={field.required}
        disabled={disabled}
        error={error}
        value={value !== undefined ? value : ""}
        onChange={(e) =>
          onChange(e.target.value === "" ? "" : parseFloat(e.target.value))
        }
        prefixIcon={<span className="text-xs font-bold">{field.currencySymbol || "₹"}</span>}
        placeholder="0.00"
        helperText={field.description}
      />
    );
  }

  // 9. Percentage Field
  if (field.type === "percentage") {
    return (
      <Input
        label={field.label}
        type="number"
        step="any"
        required={field.required}
        disabled={disabled}
        error={error}
        value={value !== undefined ? value : ""}
        onChange={(e) =>
          onChange(e.target.value === "" ? "" : parseFloat(e.target.value))
        }
        suffix={<span className="text-xs font-semibold text-slate-400">%</span>}
        placeholder="0"
        helperText={field.description}
      />
    );
  }

  // 10. Number / Decimal Field
  if (field.type === "number" || field.type === "decimal") {
    return (
      <Input
        label={field.label}
        type="number"
        step={field.type === "decimal" ? "any" : "1"}
        required={field.required}
        disabled={disabled}
        error={error}
        value={value !== undefined ? value : ""}
        onChange={(e) =>
          onChange(e.target.value === "" ? "" : parseFloat(e.target.value))
        }
        placeholder={field.placeholder || "0"}
        helperText={field.description}
      />
    );
  }

  // 11. Date / Datetime / Time
  if (field.type === "date") {
    return (
      <Input
        label={field.label}
        type="date"
        required={field.required}
        disabled={disabled}
        error={error}
        value={value || ""}
        onChange={(e) => onChange(e.target.value)}
        helperText={field.description}
      />
    );
  }

  if (field.type === "datetime") {
    return (
      <Input
        label={field.label}
        type="datetime-local"
        required={field.required}
        disabled={disabled}
        error={error}
        value={value || ""}
        onChange={(e) => onChange(e.target.value)}
        helperText={field.description}
      />
    );
  }

  if (field.type === "time") {
    return (
      <Input
        label={field.label}
        type="time"
        required={field.required}
        disabled={disabled}
        error={error}
        value={value || ""}
        onChange={(e) => onChange(e.target.value)}
        helperText={field.description}
      />
    );
  }

  // 12. Email / Phone / URL / Text
  const inputType =
    field.type === "email"
      ? "email"
      : field.type === "phone"
      ? "tel"
      : field.type === "url"
      ? "url"
      : "text";

  return (
    <Input
      label={field.label}
      type={inputType}
      required={field.required}
      disabled={disabled}
      error={error}
      value={value || ""}
      onChange={(e) => onChange(e.target.value)}
      placeholder={field.placeholder || ""}
      helperText={field.description}
    />
  );
};
